version: '3.8'

services:
  dell-port-tracer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dell-port-tracer
    ports:
      - "8443:5000"  # Updated to match production port
    environment:
      # v2.0 Features Configuration
      - USE_WINDOWS_AUTH=true
      - CPU_SAFETY_ENABLED=true
      - CPU_GREEN_THRESHOLD=40.0
      - CPU_YELLOW_THRESHOLD=60.0
      - CPU_RED_THRESHOLD=80.0
      - SWITCH_PROTECTION_ENABLED=true
      - MAX_CONNECTIONS_PER_SWITCH=8
      - MAX_TOTAL_CONNECTIONS=64
      - COMMANDS_PER_SECOND_LIMIT=10
      - SYSLOG_ENABLED=false
      - SYSLOG_SERVER=localhost
      - SYSLOG_PORT=514
      # Authentication settings - use env file for sensitive data
    env_file:
      - .env
    volumes:
      # Use bind mount for switches.json to allow runtime updates
      - type: bind
        source: ./switches.json
        target: /app/switches.json
        read_only: false
      - type: bind
        source: ./logs
        target: /app/logs
        read_only: false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    # Security settings for production
    security_opt:
      - no-new-privileges:true
    # Resource limits for v2.0 CPU monitoring
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    networks:
      - port-tracer-network

networks:
  port-tracer-network:
    driver: bridge
