apiVersion: v1
kind: Secret
metadata:
  name: port-tracer-secrets
  namespace: default
  labels:
    app: dell-port-tracer
type: Opaque
data:
  # Base64 encoded values - update these with your actual credentials
  # echo -n 'your_switch_username' | base64
  SWITCH_USERNAME: YWRtaW4=  # admin
  # echo -n 'your_switch_password' | base64
  SWITCH_PASSWORD: cGFzc3dvcmQ=  # password
  # echo -n 'oss123' | base64
  OSS_PASSWORD: b3NzMTIz  # oss123
  # echo -n 'netadmin123' | base64
  NETADMIN_PASSWORD: bmV0YWRtaW4xMjM=  # netadmin123
  # echo -n 'superadmin123' | base64
  SUPERADMIN_PASSWORD: c3VwZXJhZG1pbjEyMw==  # superadmin123
  # echo -n 'password' | base64
  WEB_PASSWORD: cGFzc3dvcmQ=  # password
  
  # Active Directory Configuration (if using Windows Auth)
  # echo -n 'ldap://kmc.int' | base64
  AD_SERVER: bGRhcDovL2ttYy5pbnQ=  # ldap://kmc.int
  # echo -n 'kmc.int' | base64
  AD_DOMAIN: a21jLmludA==  # kmc.int
  # echo -n 'DC=kmc,DC=int' | base64
  AD_BASE_DN: REM9a21jLERDPWludA==  # DC=kmc,DC=int
