apiVersion: v1
kind: ConfigMap
metadata:
  name: port-tracer-config
  namespace: default
  labels:
    app: dell-port-tracer
data:
  switches.json: |
    {
      "settings": {
        "ssh_username": "admin",
        "ssh_timeout": 10,
        "description": "Dell Switch Port Tracing Configuration",
        "version": "2.0"
      },
      "sites": {}
    }
